name: mock_event_channel
description: Temporary package to add support for mocking EventChannels in Flutter
version: 0.0.1
homepage: https://github.com/Rexios80/mock_event_channel

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  rexios_lints: ^5.0.0
